/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as AuthenticatedSiparislerimRouteImport } from './routes/_authenticated/siparislerim'
import { Route as IlanIdRouteImport } from './routes/ilan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSiparislerimRoute =
  AuthenticatedSiparislerimRouteImport.update({
    id: '/siparislerim',
    path: '/siparislerim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const IlanIdRoute = IlanIdRouteImport.update({
  id: '/ilan/$id',
  path: '/ilan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/siparislerim': typeof AuthenticatedSiparislerimRoute
  '/ilan/$id': typeof IlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/siparislerim': typeof AuthenticatedSiparislerimRoute
  '/ilan/$id': typeof IlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/giris': typeof GirisRoute
  '/_authenticated/siparislerim': typeof AuthenticatedSiparislerimRoute
  '/ilan/$id': typeof IlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/giris' | '/siparislerim' | '/ilan/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/giris' | '/siparislerim' | '/ilan/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/giris'
    | '/_authenticated/siparislerim'
    | '/ilan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GirisRoute: typeof GirisRoute
  IlanIdRoute: typeof IlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/siparislerim': {
      id: '/_authenticated/siparislerim'
      path: '/siparislerim'
      fullPath: '/siparislerim'
      preLoaderRoute: typeof AuthenticatedSiparislerimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ilan/$id': {
      id: '/ilan/$id'
      path: '/ilan/$id'
      fullPath: '/ilan/$id'
      preLoaderRoute: typeof IlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSiparislerimRoute: typeof AuthenticatedSiparislerimRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSiparislerimRoute: AuthenticatedSiparislerimRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GirisRoute: GirisRoute,
  IlanIdRoute: IlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
